import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar/Page";
import FooterSecond from "@/app/components/Footer/Page";
import { CartProvider } from "./booking/cart/cartContext";
import { JobTrackingProvider } from "@/lib/jobTracking";
import { ToastProvider } from "@/components/Toast";
import { UserEnsurer } from "@/components/UserEnsurer";
import "leaflet/dist/leaflet.css";
import { ClerkProvider } from "@clerk/nextjs";

const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <JobTrackingProvider>
          <ClerkProvider publishableKey={clerkPubKey}>
            <ToastProvider>
              <CartProvider>
                <UserEnsurer />
                <Navbar />
                <main className="flex-1">{children}</main>
                <FooterSecond />
              </CartProvider>
            </ToastProvider>
          </ClerkProvider>
        </JobTrackingProvider>
      </body>
    </html>
  );
}
